name: isis_aa_container
services:
  isis-aa:
    stdin_open: true
    tty: true
    build:
      dockerfile: Containerfile
    privileged: true  # Necessary for CIFS mounting to work
    environment:
      # Credentials for CIFS mount to archive area
      cifs_domain: ${cifs_domain}
      cifs_user: ${cifs_user}
      cifs_pass: ${cifs_pass}
      # Hostname of the computer hosting this container
      container_host_hostname: ${container_host_hostname}
    ports:
      # archive appliance UI
      - "17665:17665"
      # Needed for EPICS beacons
      - "9264:9264"
      - "9264:9264/udp"
      - "9265:9265"
      - "9265:9265/udp"
    container_name: my_aa
