name: isis_aa_container
services:
  isis-aa:
    stdin_open: true
    tty: true
    build:
      dockerfile: Containerfile
    networks:
      aanet:
          ipv4_address: 10.0.1.2
#    ports:
#      - "17665:17665"
#      - "5064:5064"
#      - "5065:5065"
    volumes:
      - "C:/Instrument/Dev/archiver-appliance/isis-aa-config/containerdata:/storage"
    container_name: my_aa
    # image: isis-aa

  isis-epics:
    networks:
      aanet:
          ipv4_address: 10.0.1.3
    ports:
      - "5064:5064"
      - "5065:5065"
    container_name: epics
    image: gilesknap/epics-base


networks:
  aanet:
    # Specify driver options
    ipam:
      driver: bridge
      config:
        - subnet: "10.0.1.0/24"
#    driver_opts:
#      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
