# Create a very simple image to perform a basic stress test
# on a host machine. This is essentially to compare the
# performance differences between an NDX virtual machine and
# say a dev machine.

# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt

# Run python.py when the container launches
CMD ["python", "./stress-primes.py"]
